version: '3.8'

services:
  postgres:
   image: postgres
   container_name:  db
   environment: 
     - POSTGRES_DB=my_store
     - POSTGRES_USER=nico
     - POSTGRES_PASSWORD=admin123

   ports:
     -  "5433:5432"

   volumes:
     - ./postgres_data:/var/lib/postgresql/data
     