version: '3.8'

services:
  postgres:
   image: postgres
   container_name:  db
   environment: 
     - POSTGRES_DB=my_store
     - POSTGRES_USER=nico
     - POSTGRES_PASSWORD=admin123

   ports:
     -  "5433:5432"

   volumes:
     - ./postgres_data:/var/lib/postgresql/data

  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=nicomartin854@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123

     