version: '3.8'

services:

#Configuracion para POSTGRES
  postgres:
   image: postgres
   container_name:  db
   environment: 
     - POSTGRES_DB=my_store
     - POSTGRES_USER=nico
     - POSTGRES_PASSWORD=admin123

   ports:
     -  "5433:5432"

   volumes:
     - ./postgres_data:/var/lib/postgresql/data

# CONFIGURacion para MYSQL
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=nicomartin854@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123

  mysql: 
    image: mysql
    container_name: mysql
    environment: 
        - MYSQL_DATABASE=my_store 
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_PORT=3306
    ports:
      - '3306-3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - PMA_HOST=mysql
          - MYSQL_ROOT_PASSWORD=admin123
      ports:
        - '8081:80'
    
    